### ISSUE TITLE
Unable to download iso image

### ISSUE THREAD

**Issue by luckykeeper** [jiangcuo/Proxmox-Arm64#10]
![image](https://user-images.githubusercontent.com/34579433/226429335-b6c978a8-bba9-4aac-a9fe-618a797e0559.png)
As the picture above, please update the download link(https://mirrors.apqa.cn/proxmox-edge/unofficialiso/proxmox-ve-arm64_7.3-1.iso), thank you very much

**Comment by jiangcuo** [comment]
Already fixed it！

**Comment by luckykeeper** [comment]
> Already fixed it！

Thanks a lot!✨🎉✨
I'll close this issue
