### ISSUE TITLE
KunPeng 920 ARM syslog err[QEMU/KVM cannot detect CPU flags on ARM]

### ISSUE THREAD

**Issue by gengsende** [jiangcuo/Proxmox-Arm64#13]
Hello,I saw the error in Syslog,Is this a bug?

`
Apr 04 09:51:18 pve81 pvestatd[2625]: QEMU/KVM cannot detect CPU flags on ARM (aarch64)
Apr 04 09:51:18 pve81 pvestatd[2625]: CPU flag detection failed, will try again after delay

`
![image](https://user-images.githubusercontent.com/23625903/229669338-6f99b448-e3f0-4581-a0ec-c22852e5e51b.png)

**Comment by jiangcuo** [comment]
it's ok. Ignore it.
