### ISSUE TITLE
A issue with pveceph installation

### ISSUE THREAD

**Issue by gengsende** [jiangcuo/Proxmox-Arm64#14]
![image](https://user-images.githubusercontent.com/23625903/229727217-bf9925e5-ef3d-42fd-bc16-02c373aafaa9.png)

I only do this by compiling ceph [https://git.proxmox.com/git/ceph.git]???

**Comment by jiangcuo** [comment]
从下面的代码可以看出，你应该是选错了ceph的版本。
```
# FIXME: remove condition with PVE 8.0, i.e., once we only support quincy+ new installations
        if ($cephver ne 'octopus' and $cephver ne 'pacific') {
            push @ceph_packages, 'ceph-volume';
        }
```
目前只有ceph  17这个版本。
