### ISSUE TITLE
Any plans for the 6.2 opt in kernel?

### ISSUE THREAD

**Issue by Fabi** [jiangcuo/Proxmox-Arm64#15]
ˆ (https://forum.proxmox.com/threads/opt-in-linux-6-2-kernel-for-proxmox-ve-7-x-available.124189/)

**Comment by jiangcuo** [comment]
I'm already testing the 6.2 kernel and it works fine now

**Comment by jiangcuo** [comment]
Add the branch v6.2   https://github.com/jiangcuo/pve-arm64-kernel/tree/v6.2
