### ISSUE TITLE
Can't join cluster because /etc/network/interfaces is not beeing used

### ISSUE THREAD

**Issue by psylou** [jiangcuo/Proxmox-Arm64#2]
Hello,

thanks for your repo and your package server. I wasn't able to get the Pi4 into my cluster because it has no interface to join on.

![image](https://user-images.githubusercontent.com/8116196/217223189-e3cd7042-e2bd-4ee9-8bbd-d9ad075a9fe0.png)

**Comment by jiangcuo** [comment]
Hi,are you create your network-config  in /etc/network/interfaces ?
