### ISSUE TITLE
Suggestion: host ISOs via github releases

### ISSUE THREAD

**Issue by kgilmer** [jiangcuo/Proxmox-Arm64#22]
Thanks for providing ISOs of Proxmox for ARM64.  I am trying it out on a orangepi-5.  I think downloads would be nice via github releases.  The file limit is 2Gb but I've found ISOs compress down nicely w/ `zip`.  It is easy to create a release and upload a file, but automation is also easy via github actions.

**Comment by kgilmer** [comment]
FWIW I'm getting about 700KB/s from US/Los Angeles area

**Comment by jiangcuo** [comment]
Thank you for your feedback, I will add the cdn in the future

**Comment by jiangcuo** [comment]
Mirrors are now published via cloudflare.
