### ISSUE TITLE
Is ZFS Working ?

### ISSUE THREAD

**Issue by ardabilal** [jiangcuo/Proxmox-Arm64#30]
Is zfs working? has anyone tried it? I will be using with U2 NVME SSD.

**Comment by jiangcuo** [comment]
zfs is available, there are 2 caveats here
1. To use your own kernel, you need to compile zfs
2. The performance of NVME SSD using zfs will be lost.

**Comment by ardabilal** [comment]
What can we use alternative to zfs ?

**Comment by jiangcuo** [comment]
zfs is really great.
But the current software raid cannot fully utilize the performance of NVME.
There is a nice [spdk](https://spdk.io) framework that solves some of the issues with NVME.
