### ISSUE TITLE
Correct repository and package links for Bookworm

### ISSUE THREAD

**Issue by Mattncb** [jiangcuo/Proxmox-Arm64#34]
Hi

If Im following the wiki installation guide to install on Bookworm would I need different commands to install the repository and packages as they both reference Bullseye, or would they work fine?

Thanks

**Comment by Mattncb** [comment]
The wiki shows the link as 

echo "deb https://global.mirrors.apqa.cn/proxmox/debian/pve bullseye port">/etc/apt/sources.list.d/pveport.list

Is that still correct?

**Comment by jiangcuo** [comment]
Yes
