### ISSUE TITLE
Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by nongze** [jiangcuo/Proxmox-Arm64#36]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
proxmox-ve is already the newest version (7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 0 B/89.9 MB of archives.
After this operation, 0 B of additional disk space will be used.
Setting up pve-manager (7.4-16) ...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binJob for pvestatd.service failed because the control process exited with error code.
See "systemctl status pvestatd.service" and "journalctl -xe" for details.
dpkg: error processing package pve-manager (--configure):
 installed pve-manager package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of proxmox-ve:
 proxmox-ve depends on pve-manager; however:
  Package pve-manager is not configured yet.

dpkg: error processing package proxmox-ve (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 pve-manager
 proxmox-ve
N: Ignoring file 'pve-firmware_3.6-4_all.deb' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Sub-process /usr/bin/dpkg returned an error code (1)
W: Operation was interrupted before it could finish
尝试了其它issues里的方法，但还是无法安装

**Comment by jiangcuo** [comment]
follow wiki Troubleshooting
