### ISSUE TITLE
[Request] Single build-from-source script/instructions

### ISSUE THREAD

**Issue by soxrok2212** [jiangcuo/Proxmox-Arm64#37]
Appreciate all the work you've put in to make this happen

 I think we would all benefit from a single script or location containing step-by-step build instructions. Right now, there are many moving parts:
- Repackage rust packages with apt-mirror
- Clone some source?
- Get a docker container (which arch should it run on?)
CDN in China is a bit slow for people outside Asia Pacific

In the long run, would be great to get this upstreamed, even if it just means building the packages for arm64 and a generic iso.

Thank you!

**Comment by jiangcuo** [comment]
Now,  Use `commit` instead `Patchs`.

https://github.com/jiangcuo/Proxmox-Port/blob/main/README.md

The Proxmox-Port code is located in the following repositories.
[zfsonlinux](https://github.com/jiangcuo/zfsonlinux)
[pve-qemu](https://github.com/jiangcuo/pve-qemu)
[pve-lxc-syscalld](https://github.com/jiangcuo/pve-lxc-syscalld)
[pve-lxcfs](https://github.com/jiangcuo/pve-lxcfs)
[pve-installer](https://github.com/jiangcuo/pve-installer)
[pve-edk2-firmware](https://github.com/jiangcuo/pve-edk2-firmware)
[proxmox-mini-journalreader](https://github.com/jiangcuo/proxmox-mini-journalreader)
[proxmox-backup](https://github.com/jiangcuo/proxmox-backup)
[proxmox-backup-restore-image](https://github.com/jiangcuo/proxmox-backup-restore-image)
[proxmox-backup-qemu](https://github.com/jiangcuo/proxmox-backup-qemu)
[pve-manager](https://github.com/jiangcuo/pve-manager)
[qemu-server](https://github.com/jiangcuo/qemu-server)

Master branch is mirror, checkout branch to arm64 / riscv64 / loongarch64 .You can view and build package.

Now, every package  can be builded by `github actions`.
