### ISSUE TITLE
error when start the vm

### ISSUE THREAD

**Issue by yuhongwei380** [jiangcuo/Proxmox-Arm64#40]
my armpve is upgrade 7.3 to 7.4-16 ; when I start the vm, it noticed that 
EFI base image '/usr/share/pve-edk2-firmware//AAVMF_CODE.ms.fd' not found 
my vm setting 
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/44333391/23ae4f33-9cee-40ea-8fb6-a947c8c51d61)

**Comment by yuhongwei380** [comment]
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/44333391/7537d369-bfc0-4e0e-a9f9-fb1ad153c622)

**Comment by jiangcuo** [comment]
What is the version of pve-edk2-firmware？
Can you show this command output `ls /usr/share/pve-edk2-firmware/ -l`

**Comment by yuhongwei380** [comment]
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/44333391/ffbdea5e-e79a-4184-9124-20d77fda4e4d)

**Comment by yuhongwei380** [comment]
> What is the version of pve-edk2-firmware？ Can you show this command output `ls /usr/share/pve-edk2-firmware/ -l`
OK
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/44333391/e0242001-0e23-4034-a580-aaa7dc2fd802)

**Comment by yuhongwei380** [comment]
the edk2-fireware 's version
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/44333391/7bd1ebb3-8fa6-413f-8774-9b5e89fcf566)

**Comment by yuhongwei380** [comment]
I can't find AAVMF_CODE.ms.fd;where i can get it!

**Comment by yuhongwei380** [comment]
> AAVMF_CODE.ms.fd

I check X86 PVE 's file , the same file alse doesn't exist .

**Comment by yuhongwei380** [comment]
I touch this file ,but  I met the new problem : when I start the vm 

generating cloud-init ISO
kvm: device requires 67108864 bytes, block backend provides 0 bytes
TASK ERROR: start failed: QEMU exited with code 1

**Comment by albertogrimana** [comment]
Hi

Try create symbolyc link
cd /usr/share/pve-edk2-firmware
ln -s AAVMF_CODE.fd AAVMF_CODE.ms.fd

I had this error and fixed with this

Regards

**Comment by yuhongwei380** [comment]
> Hi
> 
> Try create symbolyc link
> cd /usr/share/pve-edk2-firmware
> ln -s AAVMF_CODE.fd AAVMF_CODE.ms.fd
> 
> I had this error and fixed with this
> 
> Regards
> 

yeap，thank you，i remove the efi disk ，now my vm can be work！but this problem need to be fixed

**Comment by jiangcuo** [comment]
New commit f0fdbd0411888fa76a5ae248798866a9e0658251   and new verison `3.20230228-4~bpo11+2` of pve-edk2-firmware has solved this issue.

**Comment by yuhongwei380** [comment]
test OK ，My virtual machine  can start with efi-disk  and work well ！ Thank you！
