### ISSUE TITLE
Expired SSL certificate on https://mirrors.apqa.cn/

### ISSUE THREAD

**Issue by hcharbonnier** [jiangcuo/Proxmox-Arm64#49]
Hi, 
the SSL certificate on https://mirrors.apqa.cn/ expired  on 10/06/2023. 
This prevent to install packages via apt.

**Comment by jiangcuo** [comment]
Hi,
Thx, Fix.

**Comment by hcharbonnier** [comment]
Thanks. There seems to be an issue with global mirror (Cloudflare) (error 523): 
https://global.mirrors.apqa.cn/proxmox/debian/pve
