### ISSUE TITLE
No Memory and SWAP Limits for CT's

### ISSUE THREAD

**Issue by Rappelkiste98** [jiangcuo/Proxmox-Arm64#51]
I have multiple Debian Bookworm CT's running on a Raspberry PI 4B 8GB and they running fine,
but Memory and SWAP Settings from Proxmox are not working and all CT's have 8GB in "top".

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/58746798/fa042ddc-9ab0-48d8-8130-1af0b15163f5)
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/58746798/e25b4f66-25ff-4ef5-b490-f8f9ac62b604)

Do you have a Fix or a Workaround for this Problem on Raspberry PI's?

**Comment by TheBossME** [comment]
please modify cmdline.txt like 
nano /boot/cmdline.txt

put the following parameters to the end of the line

cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1

this will fix it and show memory properly

Regards
Bea

**Comment by Rappelkiste98** [comment]
Thank you very much. The Problem is solved 👍
