### ISSUE TITLE
Install proxmox 8 on Raspberry pi 4 with bookworm

### ISSUE THREAD

**Issue by Yngve0** [jiangcuo/Proxmox-Arm64#52]
I try to follow the wiki to install on a raspberry pi 4 with Bookworm. Unfortunately is stopped with this:

W: Skipping acquire of configured file 'port/binary-armhf/Packages' as repository 'https://global.mirrors.apqa.cn/proxmox/debian/pve bookworm InRelease' does not seem to provide it (sources.list entry misspelt?)

**Comment by jiangcuo** [comment]
Only for arm64.

**Comment by TheBossME** [comment]
Change the /etc/apt/sources.list.d/pveport.list to:

deb [arch=arm64] https://global.mirrors.apqa.cn/proxmox/debian/pve bookworm port

In the current bookworm arm64lite image is armhf support not removed.

Try with this and let us know.
you can also install with the tested bookworm images from raspi.Debian.net.

Regards
Beatrice
