### ISSUE TITLE
Raspberry pi 4b USB passthrough 

### ISSUE THREAD

**Issue by botardo** [jiangcuo/Proxmox-Arm64#53]
Hi, 

trying to passthrough USB3 to debian VM but no luck yet.
USB 2 works ok, I can see hard drive in VM, but when I connect it to USB 3, nothing.

I installed proxmox from ISO, running UEFI from SD card. Installed proxmox to 60 gb usb hard drive. Everything boots ok. I can see both drives in proxmox 

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/53558090/f9a095c9-72c3-4c20-a3a3-a4d78b0c7d05)

When I try to attach USB to VM, for some reason USB3 option is grayed out

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/53558090/5b51e757-4cd8-4fef-b7c2-36479753cb28)

When I start the VM, USB is present by typing lsusb command. lsblk is not showing any drives except the boot drive for the VM.
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/53558090/9dec5828-1db7-4f4d-920a-400fc4aa0532)

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/53558090/3808855e-42fc-44b5-86be-455e2b739397)

I have limited knowledge, but I would like to understand what is the problem here.

**Comment by TheBossME** [comment]
Which kernel do you use ?

**Comment by botardo** [comment]
Linux pve 6.1.24-generic #1 SMP Mon Apr 17 22:40:56 CST 2023 aarch64

**Comment by jiangcuo** [comment]
Can you share command  ` pveversion --verbose` and `lsusb -t` (on you vm and host).

**Comment by jiangcuo** [comment]
Fix Qemu-Server qemu-xhci pcie addr error

https://github.com/jiangcuo/qemu-server/commit/6e6a2c91bc841d2700a6e7803ed105fca7a8d23d

**Comment by jiangcuo** [comment]
<img width="1487" alt="image" src="https://github.com/jiangcuo/Proxmox-Arm64/assets/49061187/b0cafe56-02c7-434f-bd65-0ad8ca12b08f">

**Comment by Rappelkiste98** [comment]
@jiangcuo After your PCI fix my VM on Raspberry PI 4B doesn't start with an mounted USB.
`
kvm: -device qemu-xhci,p2=15,p3=15,id=xhci,bus=pcie.1,addr=0x1b: Bus 'pcie.1' not found
TASK ERROR: start failed: QEMU exited with code 1`

**Comment by Rappelkiste98** [comment]
I build the qemu-server from your Git Repo, on the Raspberry. Now the VM runs without Problems.
Is there a Plan to Publish this Hotfix to the Default "port" Repository?
