### ISSUE TITLE
Arch on Apt

### ISSUE THREAD

**Issue by jamesarbrown** [jiangcuo/Proxmox-Arm64#54]
After install I found there was an issue with apt update (Pi 4 Raspi Deb Bookworm)
`W: Skipping acquire of configured file 'port/binary-armhf/Packages' as repository 'https://global.mirrors.apqa.cn/proxmox/debian/pve bookworm InRelease' does not seem to provide it (sources.list entry misspelt?)`

Once Prox is installed the Pi somehow has an extra ARM arch

```
apt-config dump | grep -F "APT::Architectures" -
APT::Architectures "";
APT::Architectures:: "arm64";
APT::Architectures:: "armhf";
```

So I had to adjust the pveport.list to read
`deb [arch=arm64] https://global.mirrors.apqa.cn/proxmox/debian/pve bookworm port`

**Comment by jiangcuo** [comment]
Proxmox-Port for 64bit only.
eg. `arm64`,`riscv64`,`loong64`
