### ISSUE TITLE
Error installing pve-qemu-kvm conflict with qemu-guest-agent

### ISSUE THREAD

**Issue by pieroproietti** [jiangcuo/Proxmox-Arm64#57]
Installing proxmox-ve on Raspberry Pi 4 I get this error:

```
Preparing to unpack .../pve-qemu-kvm_8.0.2-6_arm64.deb ...
Unpacking pve-qemu-kvm (8.0.2-6) ...


dpkg: error processing archive /var/cache/apt/archives/pve-qemu-kvm_8.0.2-6_arm64.deb (--unpack):
 trying to overwrite '/usr/share/man/man7/qemu-ga-ref.7.gz', which is also in package qemu-guest-agent 1:7.2+dfsg-7+deb12u2
Errors were encountered while processing:
 /var/cache/apt/archives/pve-qemu-kvm_8.0.2-6_arm64.deb

```
![2023-11-15](https://github.com/jiangcuo/Proxmox-Arm64/assets/958613/08fa80f8-a761-4d85-904c-dc4452c00fa3)

This is something new, last week (november 11) I was able to install it without problem.

**Comment by jiangcuo** [comment]
Qemu-ga need  be installed on guest not host.
Remove it and install again.
