### ISSUE TITLE
Question about CPU Affinity

### ISSUE THREAD

**Issue by SuperKali** [jiangcuo/Proxmox-Arm64#59]
Hello,

I recently attempted to install Proxmox on a customized FriendlyElec kernel with KVM enabled. During the installation, I observed that if CPU Affinity is not configured, the CPU usage spikes to 100% without any effective utilization. Additionally, I noticed that on the virtual machine (vm), only one core is visible.

This situation is perplexing, especially when compared to the experience with Kernel 6.5 of Armbian, where this issue does not persist, though a different problem emerges.

Could you shed light on why CPU affinity is required on Kernel 6.1 but not on 6.5? I also observed the need to install pve-... to address VM boot issues, a problem unique to Kernel 6.1.

I appreciate any insights you can provide.

Thank you in advance.

**Comment by SuperKali** [comment]
With CPU affinity:

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/19473898/2be259c5-1fda-4acc-ab39-d0f93d17a2bc)

Without:

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/19473898/551c8c39-1e65-4261-a648-1d4117d93380)

**Comment by jiangcuo** [comment]
What's your pveversion 、hardware and vmconfig ?

**Comment by SuperKali** [comment]
Hello @jiangcuo,

My PVE Version is: pve-manager/7.4-16/0f39f621 (running kernel: 6.1.25)
The HW is: Nano PC T6 16GB/256GB

The VM configuration is:
``` bash
affinity: 0,1
agent: 1,fstrim_cloned_disks=1
bios: ovmf
boot: order=scsi0
cipassword: HIDDEN
ciuser: root
cores: 2
cpu: host
efidisk0: local:100/vm-100-disk-0.qcow2,efitype=4m,size=64M
ipconfig0: ip=192.168.179.100/23,gw=192.168.178.1
memory: 2048
meta: creation-qemu=8.0.2,ctime=1694352419
name: vm1-ubnt.superkali.lan
net0: virtio=5A:B7:D2:1B:1D:4B,bridge=vmbr0
numa: 0
onboot: 1
ostype: l26
scsi0: local:100/vm-100-disk-1.qcow2,size=20684M
scsi1: local:100/vm-100-cloudinit.qcow2,media=cdrom
scsihw: virtio-scsi-pci
serial0: socket
smbios1: uuid=d6f39607-f988-45e2-8de6-12b530de912e
sockets: 1
```

Packages installed:
``` bash
proxmox-ve: 7.3-1 (running kernel: 6.1.25)
pve-manager: 7.4-16 (running version: 7.4-16/0f39f621)
pve-kernel-helper: 7.3-8
ceph-fuse: 17.2.6-pve1
corosync: 3.1.7-pve1
criu: 3.16-2
glusterfs-client: 9.2-1
ifupdown: not correctly installed
ifupdown2: 3.2.0-1+pmx3
libjs-extjs: 7.0.0-1
libknet1: 1.24-pve2
libproxmox-acme-perl: 1.4.4
libproxmox-backup-qemu0: 1.3.2-1
libproxmox-rs-perl: 0.2.1
libpve-access-control: 7.4.1
libpve-apiclient-perl: 3.2-1
libpve-common-perl: 7.4-2
libpve-guest-common-perl: 4.2-4
libpve-http-server-perl: 4.2-3
libpve-rs-perl: 0.7.7
libpve-storage-perl: 7.4-3
libqb0: not correctly installed
libspice-server1: 0.14.3-2.1
lvm2: 2.03.11-2.1
lxc-pve: 5.0.2-2
lxcfs: 5.0.3-pve1
novnc-pve: 1.4.0-1
proxmox-backup-client: 2.4.1-1
proxmox-backup-file-restore: 2.4.1-1
proxmox-mail-forward: 0.1.0-1
proxmox-mini-journalreader: 1.3-1
proxmox-widget-toolkit: 3.7.3
pve-cluster: 7.3-3
pve-container: 4.4-6
pve-docs: 7.4-3
pve-edk2-firmware: 3.20220526-1
pve-firewall: 4.3-4
pve-firmware: not correctly installed
pve-ha-manager: 3.6.1
pve-i18n: 3.0.5
pve-qemu-kvm: 7.2.0-8
pve-xtermjs: 4.16.0-1
qemu-server: 7.4-4+pve1
smartmontools: 7.2-pve3
spiceterm: 3.2-2
swtpm: 0.8.0~bpo11+3
vncterm: 1.7-1
```

**Comment by jiangcuo** [comment]
rk3588 use 4 * cortex-A76  4 * cortex-A55

**Comment by SuperKali** [comment]
Hi @jiangcuo,

But this problem is not present on kernel 6.5 in armbian.

What do you think?

**Comment by jiangcuo** [comment]
https://lists.cs.columbia.edu/pipermail/kvmarm/2021-March/045368.html

**Comment by SuperKali** [comment]
definitely in the 6.5 kernel of armbian that patch was applied and so for that I don't need to configure the CPU affinity
