### ISSUE TITLE
Kunpeng 920arm page very stuck

### ISSUE THREAD

**Issue by Up-And-Coming-Lab** [jiangcuo/Proxmox-Arm64#6]
After installing the Kunpeng 920arm server by following the tutorial, I found that when I used PVE web to create a VM, the VM installation guide page was very stuck

**Comment by jiangcuo** [comment]
Can you share your vm config(`qm config {vmid}`) .
You can record  the vm installation  process if it is possible.

**Comment by Up-And-Coming-Lab** [comment]
![图片](https://user-images.githubusercontent.com/19885774/226281548-8a107ac2-61ea-4e9b-a736-128cd5742ecd.png)

**Comment by Up-And-Coming-Lab** [comment]
> Can you share your vm config(`qm config {vmid}`) . You can record the vm installation process if it is possible.

![图片](https://user-images.githubusercontent.com/19885774/226281852-c5c6651e-236b-422c-9e46-c79f9450951e.png)

**Comment by jiangcuo** [comment]
can you try another distro？ 
```https://rockylinux.org/download/```
