### ISSUE TITLE
Nodes summary status not loading after upgrade to pve 8.1.3 and know issues

### ISSUE THREAD

**Issue by anipad** [jiangcuo/Proxmox-Arm64#60]
First, thank you for porting pve 8.1.3 to ARM.

After upgrading one has to install `pve-edk2-firmware-aarch64` or VMs won't start.
See [https://forum.proxmox.com/threads/proxmox-ve-8-1-released.136960/post-609269](url)
And [https://pve.proxmox.com/wiki/Roadmap#8.1-known-issues](url)

After that most things run smoothly, except all the summary status information won't load to completion of all my nodes, see:
![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/87913403/5166e49c-cd2b-4a09-9320-73070632aa5f)
It was working in 8.0.8-1.

`pvesh get  nodes/pve2/rrddata --timeframe hour` returns
`RRD error: rrdcached@unix:/var/run/rrdcached.sock: rrd_fetch_r failed: opening '/var/lib/rrdcached/db/pve2-node/pve2': No such file or directory`

Any help is very much appreciated.

**Comment by jiangcuo** [comment]
1.   [f1a51ed3fda2c4afae667c4440073d36c735b26b](https://github.com/jiangcuo/qemu-server/tree/f1a51ed3fda2c4afae667c4440073d36c735b26b)  fix edk2 missing
2. rrd 
```
rm -rf /var/lib/rrdcached/db/pve2-node
systemctl restart pvedaemon pvestatd pveproxy pve-cluster
```

**Comment by TheBossME** [comment]
Hi, 

i've got the following while starting VM.

TASK ERROR: EFI base image '/usr/share/pve-edk2-firmware//AAVMF_CODE.fd' not found

actually installed is pve-edk2-firmware/unbekannt,now 4.2023.08-2 all 

tried this on RPi 4 hardware with 6.5 backports kernel 6.5.0-0.deb12.1-arm64 #1 SMP Debian 6.5.3-1~bpo12+1

There was a missing package for Raspberry Pi 4 System.

Fix: 
apt install pve-edk2-firmware-aarch64

regards
Bea

**Comment by semool** [comment]
The Summary Status is not loading while the code for the Kernel Name Reading is changed and not working on RPI.
I have patched the "/usr/share/pve-manager/js/pvemanagerlib.js" file and now its working fine.
```
@@ -43266,7 +43247,13 @@
 		    return data.kversion;
 		}
 		let kernel = data['current-kernel'];
-		let buildDate = kernel.version.match(/\((.+)\)\s*$/)[1] ?? 'unknown';
+		let buildDate;
+		try {
+		    buildDate = kernel.version.match(/\((.+)\)\s*$/)[1] ?? 'unknown';
+		} catch {
+		    // Patch for RPI Kernel Naming
+		    buildDate = kernel.version ?? 'unknown';
+		}
 		return `${kernel.sysname} ${kernel.release} (${buildDate})`;
 	    },
 	    value: '',
```

**Comment by jiangcuo** [comment]
> The Summary Status is not loading while the code for the Kernel Name Reading is changed and not working on RPI. I have patched the "/usr/share/pve-manager/js/pvemanagerlib.js" file and now its working fine.
> 
> ```
> @@ -43266,7 +43247,13 @@
>  		    return data.kversion;
>  		}
>  		let kernel = data['current-kernel'];
> -		let buildDate = kernel.version.match(/\((.+)\)\s*$/)[1] ?? 'unknown';
> +		let buildDate;
> +		try {
> +		    buildDate = kernel.version.match(/\((.+)\)\s*$/)[1] ?? 'unknown';
> +		} catch {
> +		    // Patch for RPI Kernel Naming
> +		    buildDate = kernel.version ?? 'unknown';
> +		}
>  		return `${kernel.sysname} ${kernel.release} (${buildDate})`;
>  	    },
>  	    value: '',
> ```

I understand  now what the problem is, because I don't have a pi and don't know what's going on.

**Comment by semool** [comment]
Yes original Proxmox Kernel Naming is:
```
uname -a
Linux proxmox 6.5.11-6-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-6 (2023-11-29T08:32Z) x86_64 GNU/Linux
```
Build Date in ().

RPI Kernel:
```
uname -a
Linux proxmox4 6.1.64-v8-16k+ #1702 SMP PREEMPT Wed Nov 29 14:26:42 GMT 2023 aarch64 GNU/Linux
```
So the Code greps the () for the Buildate ... this is not working on RPI.

**Comment by TheBossME** [comment]
Have you tried with backport 6.5 kernel for RPI ?

![image](https://github.com/jiangcuo/Proxmox-Arm64/assets/72735184/054f3387-c0d8-4d25-a622-5f488ab775b3)

**Comment by semool** [comment]
No i have not. But i have a mixed Cluster of Proxmox Machines X64 and arm64.
With my Patch it will work with any Kernel Naming.

**Comment by anipad** [comment]
> The Summary Status is not loading while the code for the Kernel Name Reading is changed and not working on RPI. I have patched the "/usr/share/pve-manager/js/pvemanagerlib.js" file and now its working fine.
> 
> ```
> @@ -43266,7 +43247,13 @@
>  		    return data.kversion;
>  		}
>  		let kernel = data['current-kernel'];
> -		let buildDate = kernel.version.match(/\((.+)\)\s*$/)[1] ?? 'unknown';
> +		let buildDate;
> +		try {
> +		    buildDate = kernel.version.match(/\((.+)\)\s*$/)[1] ?? 'unknown';
> +		} catch {
> +		    // Patch for RPI Kernel Naming
> +		    buildDate = kernel.version ?? 'unknown';
> +		}
>  		return `${kernel.sysname} ${kernel.release} (${buildDate})`;
>  	    },
>  	    value: '',
> ```

Fix works fine. Thank you again.

**Comment by jiangcuo** [comment]
fix 
https://github.com/jiangcuo/pve-manager/commit/26764642342c55bb95ebab51f4258c4db5ae9b80

**Comment by jiangcuo** [comment]
A  new package [pve-manager_8.1.3+pve1_arm64.deb](https://mirrors.apqa.cn/proxmox/debian/pve/dists/bookworm/port/binary-arm64/pve-manager_8.1.3%2Bpve1_arm64.deb) has been upload .
When rsync done, we can do `apt upgrade pve-manager`
