### ISSUE TITLE
SDN simple network creation issue

### ISSUE THREAD

**Issue by TheBossME** [jiangcuo/Proxmox-Arm64#61]
I've tried with SDN Simple network.

Got the following issue:

Parameter verification failed. (400)

net1: unable to apply pending change net1 : can't find any free ip at /usr/share/perl5/PVE/Network/SDN/Vnets.pm line 133.

Issue comes up, while subnet wasn't properly applied after creation. 

Network restart do fix it.

On Raspi's with 6.1 kernel SDN maybe will not work, didn't try it actually. VLAN with RPi default kernel 6.1 do not work.

Regards
Bea

**Comment by jiangcuo** [comment]
What's your sdn config?
If you enable the dhcp, dhcp-rang need be defined in subnet.

**Comment by jiangcuo** [comment]
Simple networks cannot use vlan.It is an internal network model for a single node.
Neither VXLAN nor EVPN requires VLAN to be enabled.

**Comment by TheBossME** [comment]
Yes, i've created the dhcp range for the SDN, my fault was to apply SDN settings after creation of the subnet.

There is no issue with SDN actually. I opened the issue before i've applied the settings. Thanks so far for all your hard work on the arm64 Proxmox port.
