### ISSUE TITLE
PVE 8.1.3  OrangePI 5 pve-edk2-firmware

### ISSUE THREAD

**Issue by albertogrimana** [jiangcuo/Proxmox-Arm64#62]
In OrangePi 5 with Armbian Debian Bookworm need to downgrade the pve-edk2-firmware with this commands

wget http://download.proxmox.com/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/pve-edk2-firmware_3.20220526-1_all.deb
dpkg -i --force-overwrite pve-edk2-firmware_3.20220526-1_all.deb
cd /usr/share/
cp -r pve-edk2-firmware pve-edk2-firmware_bkp
apt --fix-broken install
rm -rf pve-edk2-firmware
cp -r pve-edk2-firmware_bkp pve-edk2-firmware

With this apt show pve-edk2-firmware (4.2023.08-2) but really install pve-edk2-firmware_3.20220526-1

With packets pve-edk2-firmware (4.2023.08-2) don't boot virtual machine with 100% CPU in one cpu issue at least Armbian 23.11.1 with 5.10.160 rockchip kernel 
Please upgrade wiki URL 
https://github.com/jiangcuo/Proxmox-Arm64/wiki/RK3588-NOTE

Regards!

**Comment by jiangcuo** [comment]
A new package has upload for pve 8.1 `pve-edk2-firmware-aarch64=3.20220526-rockchip`.
Wiki has updated.
https://github.com/jiangcuo/Proxmox-Arm64/wiki/RK3588-NOTE
https://github.com/jiangcuo/Proxmox-Port/wiki/Rockchip-device-NOTE
I have tested it on rk3389 rockpi4 , Working now .
